# Generated by Django 4.1 on 2022-08-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_alter_phone_best_selling_alter_phone_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='pix',
            field=models.ImageField(blank=True, null=True, upload_to='pix'),
        ),
    ]
